config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'teachers#index'

  resources :teachers, only: [:index, :show] do 
    resources :courss, only: [:index, :show]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :students
    belongs_to :teacher
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :course
    has_one :teacher, through: :course
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_many :courses
    has_many :students, through: :courses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    def index
        @teacher = Teacher.find(params[:teacher_id])
        @courses = @teacher.courses
    end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
    def index 
        @teacher = Teacher.all
    end

    def show
        @teacher = Teacher.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/courses/index.html.erb
<h1><%= @teacher.name %></h1>

<% @courses.each do |course| %>
    <h1><%= course %></h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <br><br><br><br><br>

    <%= link_to 'All Teacher', teachers_path %>

  </body>
</html>

app/views/teachers/index.html.erb
<h1>Teachers</h1>

<ul>
    <% @teacher.each do |teacher| %>
        <li><%= link_to teacher.name, teacher_path(teacher) %></li>
    <% end %>

</ul>

app/views/teachers/show.html.erb
<%= image_tag @teacher.photo %>

<br><br>

<%= link_to "#{@teacher.name}'s Courses", teacher_courss_path(@teacher)  %>